repos:
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: master
    hooks:
      - id: go-fumpt
        args: [ -w ]
        name: formatting
      - id: go-vet
        name: args suspicious
      - id: go-mod-tidy
        name: normalize go.mod
